export const models_data_list  = [
   {
      id: 1,
      name: 'Anastasia Zhidkikh',
      height: 180,
      parameters: '82-61-89',
      foot_size: 40,
      hair_color: 'Блонд',
      images_folder: 'Anastasia Zhidkikh', 
   },
   {
      id: 2,
      name: 'Nastya Wolf',
      height: 180,
      parameters: '82-61-89',
      foot_size: 40,
      hair_color: 'Блонд',
      images_folder: 'Nastya Wolf', 
   },
   {
      id: 3,
      name: 'Masha Demekhina',
      height: 180,
      parameters: '82-61-89',
      foot_size: 40,
      hair_color: 'Блонд',
      images_folder: 'Masha Demekhina', 
   },
   {
      id: 4,
      name: 'Liza Adamenko',
      height: 180,
      parameters: '82-61-89',
      foot_size: 40,
      hair_color: 'Блонд',
      images_folder: 'Liza Adamenko', 
   },
   {
      id: 5,
      name: 'Daria Semenova',
      height: 180,
      parameters: '82-61-89',
      foot_size: 40,
      hair_color: 'Блонд',
      images_folder: 'Daria Semenova', 
   },
   {
      id: 6,
      name: 'Nastya Koteneva',
      height: 180,
      parameters: '82-61-89',
      foot_size: 40,
      hair_color: 'Блонд',
      images_folder:  'Nastya Koteneva', 
   },
   {
      id: 7,
      name: 'Masha Femekhina',
      height: 180,
      parameters: '82-61-89',
      foot_size: 40,
      hair_color: 'Блонд',
      images_folder: 'Masha Femekhina', 
   },
   {
      id: 8,
      name: 'Kira Maleeva',
      height: 180,
      parameters: '82-61-89',
      foot_size: 40,
      hair_color: 'Блонд',
      images_folder: 'Kira Maleeva', 
   },
   {
      id: 9,
      name: 'Ekaterina Ivanchina',
      height: 180,
      parameters: '82-61-89',
      foot_size: 40,
      hair_color: 'Блонд',
      images_folder: 'Ekaterina Ivanchina', 
   },
   {
      id: 10,
      name: 'Katya Lenskaya',
      height: 180,
      parameters: '82-61-89',
      foot_size: 40,
      hair_color: 'Блонд',
      images_folder: 'Katya Lenskaya', 
   },
   {
      id: 11,
      name: 'Masha Memekhina',
      height: 180,
      parameters: '82-61-89',
      foot_size: 40,
      hair_color: 'Блонд',
      images_folder: 'Masha Memekhina', 
   },
   {
      id: 12,
      name: 'Luba Gulaya',
      height: 180,
      parameters: '82-61-89',
      foot_size: 40,
      hair_color: 'Блонд',
      images_folder: 'Luba Gulaya', 
   },
   {
      id: 13,
      name: 'Ekaterina Kvanchina',
      height: 180,
      parameters: '82-61-89',
      foot_size: 40,
      hair_color: 'Блонд',
      images_folder: 'Ekaterina Kvanchina', 
   },
   {
      id: 14,
      name: 'Marianna',
      height: 180,
      parameters: '82-61-89',
      foot_size: 40,
      hair_color: 'Блонд',
      images_folder: 'Marianna', 
   },
   {
      id: 15,
      name: 'Tanya Reutt',
      height: 180,
      parameters: '82-61-89',
      foot_size: 40,
      hair_color: 'Блонд',
      images_folder: 'Tanya Reutt', 
   },
   {
      id: 16,
      name: 'Ksenia Vasilchenko',
      height: 180,
      parameters: '82-61-89',
      foot_size: 40,
      hair_color: 'Блонд',
      images_folder: 'Ksenia Vasilchenko', 
   },
]